name: nexora
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <3.8.0"

dependencies:
  sentry_flutter: ^8.14.2
  auto_route: ^10.0.1
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  pinput: ^5.0.1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  permission_handler: ^11.3.1
  web_socket_channel: ^3.0.1
  record: ^5.1.2
  audioplayers: ^6.1.0
  flutter_secure_storage: ^8.1.0

dev_dependencies:
  sentry_dart_plugin: ^2.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^9.2.0
  injectable_generator: ^2.7.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - .env

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: nexora-app
  org: nexora-w2
